name: .NET Library Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: self-hosted

    env:
      Solution_Name: your-solution-name.sln 
      Test_Project_Path: ./NGMainPlugin.csproj

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Check .NET version
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore $Solution_Name

    - name: Build Library
      run: dotnet build $Solution_Name --configuration ${{ matrix.configuration }} --no-restore --output ./build/

    - name: List Output Files
      run: ls -R ./build/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-DLL
        path: ./build/
